services:

  cakephp:
    build:
      context: .

    user: ${UID}

    volumes:
      - ./:/var/www/html/

    depends_on:
      - mysql

    environment:
      DEBUG: ${DEBUG}

      SECURITY_SALT: ${SECURITY_SALT}

      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      MYSQL_TEST_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_TEST_USERNAME: ${MYSQL_TEST_USERNAME}
      MYSQL_TEST_PASSWORD: ${MYSQL_TEST_PASSWORD}

      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

      FULL_BASE_URL: ${FULL_BASE_URL}

  mysql:
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --mysql-native-password=ON
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

      MYSQL_TEST_DATABASE: ${MYSQL_TEST_DATABASE}
      MYSQL_TEST_USER: ${MYSQL_TEST_USERNAME}
      MYSQL_TEST_PASSWORD: ${MYSQL_TEST_PASSWORD}

      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

    volumes:
      - 'mysql_data:/var/lib/mysql'
      - './docker/provision/mysql/init:/docker-entrypoint-initdb.d'

  minio:
    image: minio/minio
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    
    depends_on:
      - mysql
      
    environment:
      - PMA_HOSTS=mysql
      - UPLOAD_LIMIT=10G
      - MEMORY_LIMIT=2G

volumes:
    mysql_data:
    minio_storage:
